name: Sistema Biblioteca - SonarCloud

on:
  push:
    branches: [ main, master, develop ]

jobs:
  sonar:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Analizar Eureka
        working-directory: eureka-server
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=TU_PROJECT_KEY_REAL \
            -Dsonar.organization=kaymi-2026 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Analizar Gateway
        working-directory: api-gateway
        run: |
          mvn clean verify

      - name: Analizar Auth
        working-directory: auth-service
        run: |
          mvn clean verify

      - name: Analizar Libros
        working-directory: libros-service
        run: |
          mvn clean verify -DskipTests

      - name: Analizar Prestamos
        working-directory: prestamos-service
        run: |
          mvn clean verify -DskipTests

      - name: Analizar Notificaciones
        working-directory: notificaciones-service
        run: |
          mvn clean verify
